.\" Manpage for kreenshot-editor by Gregor Mi <codestruct@posteo.org>
.\" Try it out locally with $ man ./kreenshot-editor.1
.\" Examples see: http://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/
.\"           or: man xplanet
.TH kreenshot-editor 1
.TH man 1 "18 Oct 2014" "1.0" "kreenshot-editor man page"
.SH NAME
kreenshot-editor \- screenshot image editing
.SH SYNOPSIS
see http://kreenshot.wordpress.com/
.SH DESCRIPTION
see http://kreenshot.wordpress.com/
.SH OPTIONS
see $ kreenshot-editor --help
.\".SH SEE ALSO
.SH BUGS
see http://kreenshot.wordpress.com/
.SH AUTHOR
Gregor Mi <codestruct@posteo.org> and see AUTHORS
